#!/bin/bash
quotes=(
    "BOOKS! Books all the day!"
	"Dear Princess Celestia..."
	"Spike? Spike, where are you?"
	"LOOK OUT! Here comes Tom!"
	"Wow, catchy!"
	"This is my book, and I'm going to READ IT!"
)

echo ${quotes[$((RANDOM % ${#quotes[@]}))]}
