#!/bin/bash
quotes=(
    "*kreisch*"
	"RAINBOW!"
	"GLAZE!"
	"Oh Gott, ist das knuffig!"
	"Wait! What?"
	"Rainbow is best Pony!"
	"KUMQUAT!"
	"Twilight is best Princess!"
	"Pierre ist beste!"
)

echo ${quotes[$((RANDOM % ${#quotes[@]}))]}
